name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document (CV in French)
        uses: dante-ev/latex-action@latest
        with:
          root_file: cv_fr.tex
          compiler: lualatex
      - name: Uploading the PDF file into GitHub artifact
        uses: actions/upload-artifact@v4
        with:
          name: cv_fr.pdf
          path: cv_fr.pdf
